name: ml

channels:
  - conda-forge

dependencies:
  - python=3.12
  - click=8
  - ctapipe=0.21
  - graphviz=2
  - h5py
  - iminuit
  - ipympl
  - ipython
  - ipywidgets
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyterlab
  - keras
  - matplotlib=3.8
  - notebook
  - numba
  - numdifftools
  - numpy
  - pandas
  - pillow
  - pip
  - pre-commit
  - pydotplus
  - pytables
  - pytest
  - python-graphviz
  - pytorch=2.1
  - pytorch-cpu=2.1
  - ruff
  - scikit-image
  - scikit-learn=1.5
  - scipy=1.12
  - seaborn
  - torchvision
  - tqdm
  - xlrd
  - mrmr_selection
